osx_image: xcode10
language: objective-c
before_install:
    - gem update --system
    - gem install bundler
xcode_project: GenericJSON.xcodeproj
xcode_scheme: GenericJSON
after_success:
    - bundle exec pod lib lint
    - swift test
